BookStore/Models/BookViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace BookStore.Models
{
    public class BookViewModel
    {
        public int Id { get; set; }
        
        
        
        [Required( ErrorMessage ="Please enter the title of your book")]
        [StringLength(100,MinimumLength = 5)]
        public string Title { get; set; }

        

        
        [Required(ErrorMessage ="Please enter author name")]
        public string Author { get; set; }


        
        
        [StringLength(500, MinimumLength = 5)]
        [Required]
        public string Description { get; set; }
        
        
        
        
        [Required(ErrorMessage = "Please enter the category of your book")]
        [StringLength(50, MinimumLength = 5)]
        public string Category { get; set; }
        
        


        [Required]
        public int LanguageId { get; set; }
        public string Language { get; set; }




        [Required(ErrorMessage = "Please enter the Page Count of your book")]
        [Display(Name ="Page Count")]
        public int TotalPages { get; set; }



        
        [Display(Name ="Cover Photo")]
        public IFormFile BookCover { get; set; }
        public string CoverImageUrl { get; set; }




        [Display(Name = "Book PDF")]
        public IFormFile BookPdf { get; set; }
        public string BookPdfUrl { get; set; }



        
        [Display(Name ="Gallery Images")]
        public IFormFileCollection GalleryFiles { get; set; }
        public List<GalleryImageViewModel> Gallery { get; set; }

    }
}

BookStore/Controllers/BookController.cs
using BookStore.Helpers;
using BookStore.Models;
using BookStore.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.Runtime.CompilerServices;
using static Microsoft.EntityFrameworkCore.DbLoggerCategory;

namespace BookStore.Controllers
{
    [Authorize]
    public class BookController : Controller
    {
        private readonly IBookRepository bookRepository;
        private readonly FilesHelper filesHelper;
        public BookController(IBookRepository bookRepository,FilesHelper filesHelper) 
        {
            this.bookRepository = bookRepository;
            this.filesHelper = filesHelper;
        }


        public async Task<IActionResult> AllBooks()
        {
            List<BookViewModel> models = await bookRepository.GetAllBooksAsync();
            return View(models);
        }

        [Authorize(Roles ="Admin")]
        public async Task<IActionResult> Create ()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(BookViewModel viewModel)
        {
            if(ModelState.IsValid)
            {
                if(viewModel.BookCover == null)
                    ModelState.AddModelError("BookCover", "please add Book Cover Image");

                if (viewModel.BookPdf == null)
                    ModelState.AddModelError("BookPdf", "please add Book PDF");

                if(viewModel.GalleryFiles == null)
                    ModelState.AddModelError("GalleryFiles", "please add Gallery Images");

                if (ModelState.ErrorCount>0)
                    return View();

                if (await bookRepository.AddNewBookAsync(viewModel) != 0)
                    return RedirectToAction("AllBooks");
                else
                    throw new Exception("Error Occured while adding new book");
            }

            return View();
        }

        public async Task<IActionResult> Details(int id)
        {
            BookViewModel model = await bookRepository.GetBookByIdAsync(id);
            return View(model);
        }

        public async Task<IActionResult> Delete(int id)
        {
            if(await bookRepository.DeleteBookAsync(id)!=0)
                return RedirectToAction("AllBooks");

            throw new Exception("Error Occured While Deleting");
        }

        public async Task<IActionResult> Update(int id)
        {
            BookViewModel model = await bookRepository.GetBookByIdAsync(id);
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(BookViewModel viewModel)
        {
            if (ModelState.IsValid)
            {
                if(await bookRepository.UpdateBookAsync(viewModel)!=0)
                    return RedirectToAction("AllBooks");

                throw new Exception("Error occured While Updating");
            }
            return View();
        }
    }
}

BookStore/Views/Book/AllBooks.cshtml
@{
    ViewData["Title"] = "All books";
}
@model List<BookViewModel>

<div class="container">
    <h3 class="display-4">All books</h3>
    <div class="row">

        @foreach (var book in Model)
        {
            <div class="col-md-4">
                <div class="card mb-4 shadow-sm">
                    <img src=@("/book/cover/"+book.CoverImageUrl) class="img-thumbnail" />
                    <div class="card-body">
                        <h3 class="card-title">@book.Title</h3>
                        <p class="card-text">@(string.IsNullOrEmpty(book.Description) ? "Description is not availabe" : book.Description)</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a asp-controller="Book" asp-action="Details" asp-route-id="@book.Id"
                                   class="btn btn-sm btn-outline-secondary">View details</a>
                            </div>
                            <div class="btn-group">
                                <a asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id"
                                   class="btn btn-sm btn-outline-secondary text-danger">Delete This Book</a>
                            </div>
                            <small class="text-muted">@(string.IsNullOrEmpty(book.Author) ? "NA" : book.Author)</small>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

BookStore/Views/Book/Create.cshtml
@using BookStore.Repository
@inject ILanguageRepository languageRepo
@model BookViewModel
@{
    ViewData["Title"] = "Add new book";
}
<div class="container">
    <h3 class="display-4">Add new book</h3>
    <hr />

<form method="post" enctype="multipart/form-data" asp-action="Create" asp-controller="Book">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="@Model.Title" class="control-label"></label>
        <input asp-for="@Model.Title" class="form-control" />
        <span asp-validation-for="@Model.Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="@Model.Author" class="control-label"></label>
        <input asp-for="@Model.Author" class="form-control" />
        <span asp-validation-for="@Model.Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <textarea asp-for="Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Category" class="control-label"></label>
        <input asp-for="Category" class="form-control"></input>
        <span asp-validation-for="Category" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="TotalPages" class="control-label"></label>
        <input asp-for="TotalPages" class="form-control" />
        <span asp-validation-for="TotalPages" class="text-danger"></span>
    </div>

        <div class="form-group">
            <label asp-for="LanguageId" class="control-label"></label>
            <select asp-for="LanguageId" class="form-control" asp-items="(await languageRepo.GetAllLanguagesAsync()).Select(x=> new SelectListItem() { Text = x.Name, Value = x.Id.ToString()})">
                <option value="">Please choose your language</option>
            </select>
            <span asp-validation-for="LanguageId" class="text-danger"></span>
        </div>

        <div class="input-group mb-3">
            <div class="custom-file">
                <input asp-for="BookCover" class="custom-file-input" id="inputGroupFile03">
                <label asp-for="BookCover" class="custom-file-label">Choose Cover Image</label>
            </div>
            <span asp-validation-for="@Model.BookCover" class="text-danger"></span>
        </div>

    <div class="form-group">
        <label asp-for="GalleryFiles" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="GalleryFiles" class="custom-file-input" id="customFile">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
        <span asp-validation-for="GalleryFiles" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BookPdf" class="control-label"></label>
        <div class="custom-file">
            <input asp-for="BookPdf" class="custom-file-input" id="customFile">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
        <span asp-validation-for="BookPdf" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Add book" class="btn btn-primary" />
    </div>
</form>
</div>

BookStore/Views/Book/Details.cshtml
@{
    ViewData["Title"] = "Book detail " + Model.Title;
}
@model BookViewModel

<div class="container">
    <h3 class="display-4">Book details</h3>
    <div class="row">
        <div class="col-md-6">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-inner">
                    @for (int i = 0; i < Model.Gallery.Count(); i++)
                    {
                        <div class="carousel-item @( i == 0 ? "active" : "" )">
                            <img src="@("/book/gallery/"+Model.Gallery[i].Url)" class="d-block w-100" alt="@Model.Gallery[i].Name">
                        </div>
                    }
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="visually-hidden">Next</span>
                </button>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h1>@Model.Title</h1>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12 text-primary">
                    <span class="label label-primary">By: </span>
                    <span class="monospaced">@Model.Author</span>
                </div>
            </div>

            <div class="row">
                <div class="col-md-12">
                    <p class="description">
                        @Model.Description
                    </p>
                </div>
            </div>

            <div class="row">
                <div class="col-md-4">
                    <a href="@("/book/pdf/"+Model.BookPdfUrl)" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal">
                        Read now
                    </a>
                </div>
                <div class="col-md-4">
                    <a asp-action="Update" asp-controller="Book" asp-route-id="@Model.Id" class="btn btn-outline-primary" data-toggle="modal" data-target="#exampleModal">
                        Update Book
                    </a>
                </div>
            </div>
            <hr />

            <ul class="list-group">
                <li class="list-group-item"><span class="font-weight-bold">Category - </span> @Model.Category</li>
                <li class="list-group-item"><span class="font-weight-bold">Total pages - </span> @Model.TotalPages</li>
                <li class="list-group-item"><span class="font-weight-bold">Language - </span> @Model.Language</li>
            </ul>
        </div>
    </div>
</div>

BookStore/Views/Book/Update.cshtml
@using BookStore.Repository
@inject ILanguageRepository languageRepo
@model BookViewModel
@{
    ViewData["Title"] = "Update Book";
}
<div class="container">
    <h3 class="display-4">Update Book</h3>
    <hr />

    <form method="post" enctype="multipart/form-data" asp-action="Update" asp-controller="Book">
        <div asp-validation-summary="All" class="text-danger"></div>

        <input hidden name="Id" value="@Model.Id"></input>
        <div class="form-group">
            <label asp-for="@Model.Title" class="control-label"></label>
            <input asp-for="@Model.Title" class="form-control" />
            <span asp-validation-for="@Model.Title" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="@Model.Author" class="control-label"></label>
            <input asp-for="@Model.Author" class="form-control" />
            <span asp-validation-for="@Model.Author" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description" class="control-label"></label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Category" class="control-label"></label>
            <input asp-for="Category" class="form-control"></input>
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="TotalPages" class="control-label"></label>
            <input asp-for="TotalPages" class="form-control" />
            <span asp-validation-for="TotalPages" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="LanguageId" class="control-label"></label>
            <select asp-for="LanguageId" class="form-control" asp-items="(await languageRepo.GetAllLanguagesAsync()).Select(x=> new SelectListItem() { Text = x.Name, Value = x.Id.ToString()})">
                <option value="">Please choose your language</option>
            </select>
            <span asp-validation-for="LanguageId" class="text-danger"></span>
        </div>

        <div class="input-group mb-3">
            <div class="custom-file">
                <input asp-for="BookCover" class="custom-file-input" id="inputGroupFile03">
                <label asp-for="BookCover" class="custom-file-label">Choose Cover Image</label>
            </div>
            <span asp-validation-for="@Model.BookCover" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="GalleryFiles" class="control-label"></label>
            <div class="custom-file">
                <input asp-for="GalleryFiles" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <span asp-validation-for="GalleryFiles" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="BookPdf" class="control-label"></label>
            <div class="custom-file">
                <input asp-for="BookPdf" class="custom-file-input" id="customFile">
                <label class="custom-file-label" for="customFile">Choose file</label>
            </div>
            <span asp-validation-for="BookPdf" class="text-danger"></span>
        </div>
        <div class="form-group">
            <input type="submit" value="Update" class="btn btn-primary" />
        </div>
    </form>
</div>